version: "3.1"
services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=awesome_places_development
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=dbuser
    depends_on:
      - redis
  redis:
    image: redis
    ports:
      - "6379:6379"

volumes:
  dbdata:
