version: 2.1

orbs:
  ruby: circleci/ruby@1.1.0
  node: circleci/node@2

jobs:
  build:
    docker:
      - image: cimg/ruby:2.7.1
    steps:
      - checkout
      - ruby/install-deps
  test:
    docker:
      - image: cimg/ruby:2.7.1
      - image: circleci/postgres:9.5-alpine
        environment:
          POSTGRES_USER: dbuser
          POSTGRES_DB: awesome_places_test
          POSTGRES_PASSWORD: dbpass
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
      PGHOST: 127.0.0.1
      PGUSER: postgres
      PGPASSWORD: postgres
      RAILS_ENV: test
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432
      - run:
          name: Database setup
          command: bundle exec rails db:schema:load --trace

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build